language: java
script:
- sh .trigger-travis.sh
env:
  global:
    secure: utadmj04BwFXLf0yhepr2Qo0l0G3ZBqJ3UbHMLOM//OgPlFLwe+1DtIutg1WfjNU6gW9incTQDb06+wGXAy+zjZfVbahIw5GDNGNSp3aL6p2/GuXQ+q31dLg5TUP+XHSJMY5xDBm03BwNH32g5dcD1JVK6+2ny1ggFIp3FeDqp3gFA7fG40rw6aMqEPguNc+OePrfa9whOPD7j+0PQnm9lZ+muuWGC89LoY7EMngIOOUOMlYdg1gBifWqJ1X8nMV7rjQSge069nuqu4PqspMMVFJCDyoVRxuE/QmqT29DvdRaRvIFPR/Idc+N/75ltlKSbCXFDw0wap+/hF+Htx9Y2kaj54XqYQ1tGtuOxRpoxgkhEZNvlewVEP9ljuaQrQKWuhVc+q+XVgRQKzKrYRz2/L3aLtqqTNk4VgPBCvRpxwy3XtEljwnv/eYPwoVEgAHtTf/b7ZrOso6CO0hfz/noU0zYOcWIKgFnTNICJEGncsGNh3GsrDqkB4YshpWAYZlOHoAohM2PyNnm70Hf2mwC5XNr+fAwpw7tsZCzY7K73fncNk+iuru6mVAPEcaeX6O/HVd6/G2P6RaAwQYCFcXVoivzC+XUB0t88l/HxDgK2jLFnHvJAbHBJXlbony09BDucj4Fg7MHrCInUeVnbtM7gy7PZLKWZpjYIzRgyhSQY4=
