---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: configmap-bridge
  name: configmap-bridge
spec:
  replicas: 1
  selector:
    name: configmap-bridge
  template:
    metadata:
      labels:
        name: configmap-bridge
    spec:
      containers:
      - image: configmap-bridge
        livenessProbe:
          tcpSocket:
            port: 5672
        name: bridge
        ports:
        - containerPort: 5672
          name: amqp
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - bridge
      from:
        kind: ImageStreamTag
        name: configmap-bridge:latest
    type: ImageChange
