apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ebench-agent
  labels:
    name: ebench-agent
spec:
  replicas: 1
  selector:
    name: ebench-agent
  template:
    metadata:
      labels:
        name: ebench-agent
    spec:
      containers:
      - name: ebench-agent
        image: enmasseproject/ebench-agent:latest
        ports:
            - containerPort: 8080
        env:
        - name: BENCH_DURATION
          value: "300"
        - name : BENCH_MSG_SIZE
          value: "128"
        - name : BENCH_ADDRESS
          value: anycast
        - name : BENCH_CLIENTS
          value: "1"
