---
apiVersion: v1
kind: Template
metadata:
  name: enmasse
objects:
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: queue
    name: queue-inmemory
  objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: queue-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: artemis
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            livenessProbe:
              tcpSocket:
                port: amqp
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: router
            livenessProbe:
              tcpSocket:
                port: amqp
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
          volumes:
          - emptyDir: {}
            name: vol-${ADDRESS}
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - router
          from:
            kind: ImageStreamTag
            name: router:latest
        type: ImageChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - broker
          from:
            kind: ImageStreamTag
            name: artemis:latest
        type: ImageChange
  - apiVersion: v1
    data:
      address: "${ADDRESS}"
      multicast: 'false'
      store-and-forward: 'true'
    kind: ConfigMap
    metadata:
      labels:
        type: address-config
      name: config-${ADDRESS}
  parameters:
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: Storage capacity required for volume claims
    name: STORAGE_CAPACITY
    value: 2Gi
  - description: The address to use for the queue
    name: ADDRESS
    required: true
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: queue
    name: queue-persisted
  objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-${ADDRESS}
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: "${STORAGE_CAPACITY}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: queue-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: artemis
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            livenessProbe:
              tcpSocket:
                port: amqp
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: router
            livenessProbe:
              tcpSocket:
                port: amqp
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
          volumes:
          - name: vol-${ADDRESS}
            persistentVolumeClaim:
              claimName: pvc-${ADDRESS}
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - router
          from:
            kind: ImageStreamTag
            name: router:latest
        type: ImageChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - broker
          from:
            kind: ImageStreamTag
            name: artemis:latest
        type: ImageChange
  - apiVersion: v1
    data:
      address: "${ADDRESS}"
      multicast: 'false'
      store-and-forward: 'true'
    kind: ConfigMap
    metadata:
      labels:
        type: address-config
      name: config-${ADDRESS}
  parameters:
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: Storage capacity required for volume claims
    name: STORAGE_CAPACITY
    value: 2Gi
  - description: The address to use for the queue
    name: ADDRESS
    required: true
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: topic
    name: topic-inmemory
  objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: topic-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: artemis
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            livenessProbe:
              tcpSocket:
                port: amqp
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: router
            livenessProbe:
              tcpSocket:
                port: amqp
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${TOPIC_FORWARDER_IMAGE}"
            livenessProbe:
              httpGet:
                path: "/health"
                port: health
            name: forwarder
            ports:
            - containerPort: 8080
              name: health
          volumes:
          - emptyDir: {}
            name: vol-${ADDRESS}
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - router
          from:
            kind: ImageStreamTag
            name: router:latest
        type: ImageChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - broker
          from:
            kind: ImageStreamTag
            name: artemis:latest
        type: ImageChange
  - apiVersion: v1
    data:
      address: "${ADDRESS}"
      multicast: 'true'
      store-and-forward: 'true'
    kind: ConfigMap
    metadata:
      labels:
        type: address-config
      name: config-${ADDRESS}
  parameters:
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: Storage capacity required for volume claims
    name: STORAGE_CAPACITY
    value: 2Gi
  - description: The address to use for the topic
    name: ADDRESS
    required: true
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: topic
    name: topic-persisted
  objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-${ADDRESS}
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: "${STORAGE_CAPACITY}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: topic-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: artemis
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            livenessProbe:
              tcpSocket:
                port: amqp
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: router
            livenessProbe:
              tcpSocket:
                port: amqp
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${TOPIC_FORWARDER_IMAGE}"
            livenessProbe:
              httpGet:
                path: "/health"
                port: health
            name: forwarder
            ports:
            - containerPort: 8080
              name: health
          volumes:
          - name: vol-${ADDRESS}
            persistentVolumeClaim:
              claimName: pvc-${ADDRESS}
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - router
          from:
            kind: ImageStreamTag
            name: router:latest
        type: ImageChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - broker
          from:
            kind: ImageStreamTag
            name: artemis:latest
        type: ImageChange
  - apiVersion: v1
    data:
      address: "${ADDRESS}"
      multicast: 'true'
      store-and-forward: 'true'
    kind: ConfigMap
    metadata:
      labels:
        type: address-config
      name: config-${ADDRESS}
  parameters:
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: Storage capacity required for volume claims
    name: STORAGE_CAPACITY
    value: 2Gi
  - description: The address to use for the topic
    name: ADDRESS
    required: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: configmap-bridge
  spec:
    dockerImageRepository: "${CONFIGMAP_BRIDGE_IMAGE}"
    importPolicy:
      scheduled: true
    tags:
    - annotations:
        description: ConfigMap AMQP Bridge
        tags: enmasse,messaging,configmap,amqp
        version: '1.0'
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: configmap-bridge
    name: configmap-bridge
  spec:
    replicas: 1
    selector:
      name: configmap-bridge
    template:
      metadata:
        labels:
          name: configmap-bridge
      spec:
        containers:
        - image: configmap-bridge
          livenessProbe:
            tcpSocket:
              port: amqp
          name: bridge
          ports:
          - containerPort: 5672
            name: amqp
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - bridge
        from:
          kind: ImageStreamTag
          name: configmap-bridge:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ragent
  spec:
    dockerImageRepository: "${RAGENT_IMAGE}"
    importPolicy:
      scheduled: true
    tags:
    - annotations:
        description: EnMasse router agent
        tags: enmasse,messaging,ragent,config,amqp
        version: '1.0'
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: ragent
    name: ragent
  spec:
    replicas: 1
    selector:
      name: ragent
    template:
      metadata:
        labels:
          name: ragent
      spec:
        containers:
        - image: ragent
          livenessProbe:
            tcpSocket:
              port: amqp
          name: ragent
          ports:
          - containerPort: 55672
            name: amqp
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ragent
        from:
          kind: ImageStreamTag
          name: ragent:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: router
  spec:
    dockerImageRepository: "${ROUTER_IMAGE}"
    importPolicy:
      scheduled: true
    tags:
    - annotations:
        description: Qpid Dispatch Router
        tags: enmasse,messaging,router,qpid,amqp
        version: '1.0'
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: qdrouterd
    name: qdrouterd
  spec:
    replicas: 1
    selector:
      name: qdrouterd
    template:
      metadata:
        labels:
          capability: router
          name: qdrouterd
      spec:
        containers:
        - env:
          - name: LINK_CAPACITY
            value: "${ROUTER_LINK_CAPACITY}"
          image: router
          livenessProbe:
            tcpSocket:
              port: amqp
          name: router
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - router
        from:
          kind: ImageStreamTag
          name: router:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: artemis
  spec:
    dockerImageRepository: "${BROKER_IMAGE}"
    importPolicy:
      scheduled: true
    tags:
    - annotations:
        description: Artemis message broker
        tags: enmasse,messaging,activemq,artemis,broker,amqp
        version: '1.0'
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: subserv
  spec:
    dockerImageRepository: "${SUBSERV_IMAGE}"
    importPolicy:
      scheduled: true
    tags:
    - annotations:
        description: Subscription service
        tags: enmasse,messaging,amqp,subscription,topic
        version: '1.0'
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: subserv
    name: subserv
  spec:
    replicas: 1
    selector:
      name: subserv
    template:
      metadata:
        labels:
          name: subserv
      spec:
        containers:
        - image: subserv
          livenessProbe:
            tcpSocket:
              port: amqp
          name: subserv
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - subserv
        from:
          kind: ImageStreamTag
          name: subserv:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: messaging
  spec:
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      capability: router
- apiVersion: v1
  kind: Service
  metadata:
    name: ragent
  spec:
    ports:
    - port: 55672
      protocol: TCP
      targetPort: 55672
    selector:
      name: ragent
- apiVersion: v1
  kind: Service
  metadata:
    name: configuration
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      name: configmap-bridge
- apiVersion: v1
  kind: Service
  metadata:
    name: subscription
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      name: subserv
parameters:
- description: The image to use for the router
  name: ROUTER_IMAGE
  value: gordons/qdrouterd:latest
- description: The default image to use as broker
  name: BROKER_IMAGE
  value: enmasseproject/artemis:latest
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: The image to use for the configmap notification bridge
  name: CONFIGMAP_BRIDGE_IMAGE
  value: enmasseproject/configmap-bridge:latest
- description: The docker image to use for the storage controller
  name: STORAGE_CONTROLLER_IMAGE
  value: enmasseproject/storage-controller:latest
- description: The image to use for the router agent
  name: RAGENT_IMAGE
  value: enmasseproject/ragent:latest
- description: The image to use for the subscription services
  name: SUBSERV_IMAGE
  value: enmasseproject/subserv:latest
