apiVersion: v1
kind: Service
metadata:
  name: messaging
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
    protocol: TCP
  - port: 5671
    targetPort: 5671
    name: amqps
    protocol: TCP
  selector:
    capability: router
