---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: qdrouterd
  name: qdrouterd
spec:
  replicas: 1
  selector:
    name: qdrouterd
  template:
    metadata:
      labels:
        capability: router
        name: qdrouterd
    spec:
      containers:
      - env:
        - name: LINK_CAPACITY
          value: "${ROUTER_LINK_CAPACITY}"
        image: "${ROUTER_IMAGE}"
        name: router
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
