apiVersion: v1
kind: ReplicationController
metadata:
  name: qdrouterd
  labels:
    name: qdrouterd
spec:
  replicas: 1
  selector:
    name: qdrouterd
  template:
    metadata:
      labels:
        name: qdrouterd
        capability: router
    spec:
      containers:
      - name: master
        image: gordons/qdrouterd:v10
        env:
        - name: LINK_CAPACITY
          value: '50'
        ports:
        - containerPort: 5672
