---
apiVersion: v1
kind: Template
metadata:
  labels:
    addressType: queue
  name: queue-persisted
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-${ADDRESS}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "${STORAGE_CAPACITY}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: queue-${ADDRESS}
  spec:
    replicas: 1
    selector:
      address: "${ADDRESS}"
      role: broker
    template:
      metadata:
        labels:
          address: "${ADDRESS}"
          capability: router
          role: broker
      spec:
        containers:
        - env:
          - name: QUEUE_NAME
            value: "${ADDRESS}"
          image: artemis
          lifecycle:
            preStop:
              exec:
                command:
                - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
          livenessProbe:
            tcpSocket:
              port: amqp
          name: broker
          ports:
          - containerPort: 5673
            name: amqp
          - containerPort: 61616
            name: core
          volumeMounts:
          - mountPath: "/var/run/artemis"
            name: vol-${ADDRESS}
        - env:
          - name: LINK_CAPACITY
            value: "${ROUTER_LINK_CAPACITY}"
          - name: QUEUE_NAME
            value: "${ADDRESS}"
          image: router
          livenessProbe:
            tcpSocket:
              port: amqp
          name: router
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
        volumes:
        - name: vol-${ADDRESS}
          persistentVolumeClaim:
            claimName: pvc-${ADDRESS}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - router
        from:
          kind: ImageStreamTag
          name: router:${ENMASSE_VERSION}
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - broker
        from:
          kind: ImageStreamTag
          name: artemis:${ENMASSE_VERSION}
      type: ImageChange
- apiVersion: v1
  data:
    address: "${ADDRESS}"
    multicast: 'false'
    store-and-forward: 'true'
  kind: ConfigMap
  metadata:
    labels:
      type: address-config
    name: config-${ADDRESS}
parameters:
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: Storage capacity required for volume claims
  name: STORAGE_CAPACITY
  value: 2Gi
- description: EnMasse version
  name: ENMASSE_VERSION
  value: latest
- description: The address to use for the queue
  name: ADDRESS
  required: true
