---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: ragent
  name: ragent
spec:
  replicas: 1
  selector:
    name: ragent
  template:
    metadata:
      labels:
        name: ragent
    spec:
      containers:
      - image: ragent
        livenessProbe:
          tcpSocket:
            port: amqp
        name: ragent
        ports:
        - containerPort: 55672
          name: amqp
          protocol: TCP
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ragent
      from:
        kind: ImageStreamTag
        name: ragent:latest
    type: ImageChange
