---
apiVersion: v1
kind: ImageStream
metadata:
  name: ragent
spec:
  dockerImageRepository: enmasseproject/ragent:latest
  importPolicy:
    scheduled: true
  tags:
  - annotations:
      description: EnMasse router agent
      tags: enmasse,messaging,ragent,config,amqp
      version: '1.0'
    name: latest
