---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ragent
  name: ragent
spec:
  replicas: 1
  selector:
    name: ragent
  template:
    metadata:
      labels:
        name: ragent
    spec:
      containers:
      - image: enmasseproject/ragent:latest
        name: master
        ports:
        - containerPort: 55672
          protocol: TCP
