apiVersion: v1
kind: DeploymentConfig
metadata:
  name: storage-controller
  labels:
    name: storage-controller
spec:
  replicas: 1
  selector:
    name: storage-controller
  template:
    metadata:
      labels:
        name: storage-controller
    spec:
      serviceAccount: deployer
      containers:
      - name: master
        image: enmasseproject/storage-controller:latest
