---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: storage-controller
  name: storage-controller
spec:
  replicas: 1
  selector:
    name: storage-controller
  strategy:
    rollingParams:
      maxSurge: 0
    type: Rolling
  template:
    metadata:
      labels:
        name: storage-controller
    spec:
      containers:
      - image: storage-controller
        livenessProbe:
          httpGet:
            path: "/health"
            port: health
        name: controller
        ports:
        - containerPort: 8080
          name: health
      serviceAccount: deployer
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - controller
      from:
        kind: ImageStreamTag
        name: storage-controller:latest
    type: ImageChange
