---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: storage-controller
  name: storage-controller
spec:
  replicas: 1
  selector:
    name: storage-controller
  template:
    metadata:
      labels:
        name: storage-controller
    spec:
      containers:
      - image: enmasseproject/storage-controller:latest
        name: controller
      serviceAccount: deployer
