---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: subserv
  name: subserv
spec:
  replicas: 1
  selector:
    name: subserv
  template:
    metadata:
      labels:
        name: subserv
    spec:
      containers:
      - image: subserv
        livenessProbe:
          tcpSocket:
            port: amqp
        name: subserv
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - subserv
      from:
        kind: ImageStreamTag
        name: subserv:latest
    type: ImageChange
