---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: subserv
  name: subserv
spec:
  replicas: 1
  selector:
    name: subserv
  template:
    metadata:
      labels:
        name: subserv
    spec:
      containers:
      - image: enmasseproject/subserv:latest
        name: subserv
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
