apiVersion: v1
kind: DeploymentConfig
metadata:
  name: storage-controller
  labels:
    name: storage-controller
spec:
  replicas: 1
  selector:
    name: storage-controller
  template:
    metadata:
      labels:
        name: storage-controller
    spec:
      serviceAccount: deployer
      containers:
      - name: master
        image: enmasseproject/storage-controller:latest
        env:
        - name: ROUTER_CERTS_SECRET_NAME
          value: qdrouterd-certs
        - name: ROUTER_CERTS_PATH
          value: /etc/qpid-dispatch/ssl
