apiVersion: v1
kind: Template
metadata:
  name: enmasse
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: configuration
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      name: configmap-bridge
- apiVersion: v1
  kind: Service
  metadata:
    name: messaging
  spec:
    ports:
    - port: 5672
      targetPort: 5672
      name: amqp
      protocol: TCP
    - port: 5671
      targetPort: 5671
      name: amqps
      protocol: TCP
    selector:
      capability: router
- apiVersion: v1
  kind: Service
  metadata:
    name: ragent
  spec:
    ports:
    - port: 55672
      protocol: TCP
      targetPort: 55672
    selector:
      name: ragent
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: configmap-bridge
    name: configmap-bridge
  spec:
    replicas: 1
    selector:
      name: configmap-bridge
    template:
      metadata:
        labels:
          name: configmap-bridge
      spec:
        containers:
        - image: "${CONFIGMAP_BRIDGE_IMAGE}"
          name: bridge
          ports:
          - containerPort: 5672
            protocol: TCP
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: qdrouterd
    name: qdrouterd
  spec:
    replicas: 1
    selector:
      name: qdrouterd
    template:
      metadata:
        labels:
          capability: router
          name: qdrouterd
      spec:
        volumes:
        - name: ssl-certs
          secret:
            secretName: qdrouterd-certs
        containers:
        - image: "${ROUTER_IMAGE}"
          name: master
          ports:
          - containerPort: 5672
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/qpid-dispatch/ssl
            readOnly: true
            name: ssl-certs
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: ragent
    name: ragent
  spec:
    replicas: 1
    selector:
      name: ragent
    template:
      metadata:
        labels:
          name: ragent
      spec:
        containers:
        - image: "${RAGENT_IMAGE}"
          name: master
          ports:
          - containerPort: 55672
            protocol: TCP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: storage-controller
    name: storage-controller
  spec:
    replicas: 1
    selector:
      name: storage-controller
    template:
      metadata:
        labels:
          name: storage-controller
      spec:
        serviceAccount: deployer
        containers:
        - image: "${STORAGE_CONTROLLER_IMAGE}"
          name: master
        env:
        - name: BROKER_IMAGE
          value: "${BROKER_IMAGE}"
        - name: ROUTER_IMAGE
          value: "${ROUTER_IMAGE}"
        - name: ROUTER_CERTS_SECRET_NAME
          value: qdrouterd-certs
        - name: ROUTER_CERTS_PATH
          value: /etc/qpid-dispatch/ssl
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: maas
  data:
    json: |
      {
          "myqueue": { "store_and_forward":true, "multicast":false },
          "anycast": { "store_and_forward":false, "multicast":false },
          "broadcast": { "store_and_forward":false, "multicast":true }
      }
parameters:
  - name: BROKER_IMAGE
    value: gordons/artemis:latest
    description: The image to use for the broker
  - name: ROUTER_IMAGE
    description: "The image to use for the router"
    value: gordons/qdrouterd:v9
  - name: CONFIGMAP_BRIDGE_IMAGE
    description: "The image to use for the configmap notification bridge"
    value: "enmasseproject/configmap-bridge:latest"
  - name: STORAGE_CONTROLLER_IMAGE
    description: "The docker image to use for the storage controller"
    value: "enmasseproject/storage-controller:latest"
  - name: RAGENT_IMAGE
    description: "The image to use for the router agent"
    value: "enmasseproject/ragent:latest"
