apiVersion: v1
kind: ReplicationController
metadata:
  name: qdrouterd
  labels:
    name: qdrouterd
spec:
  replicas: 1
  selector:
    name: qdrouterd
  template:
    metadata:
      labels:
        name: qdrouterd
        capability: router
    spec:
      volumes:
      - name: ssl-certs
        secret:
          secretName: qdrouterd-certs
      containers:
      - name: master
        image: gordons/qdrouterd:v10
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: /etc/qpid-dispatch/ssl
          readOnly: true
          name: ssl-certs
