---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: qdrouterd
  name: qdrouterd
spec:
  replicas: 1
  selector:
    name: qdrouterd
  template:
    metadata:
      labels:
        capability: router
        name: qdrouterd
    spec:
      containers:
      - env:
        - name: LINK_CAPACITY
          value: "${ROUTER_LINK_CAPACITY}"
        image: "${QDROUTER_IMAGE}"
        name: router
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 5671
          name: amqps
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/qpid-dispatch/ssl"
          name: ssl-certs
          readOnly: true
      volumes:
      - name: ssl-certs
        secret:
          secretName: qdrouterd-certs
