---
apiVersion: v1
kind: Service
metadata:
  name: messaging
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    capability: router
