apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-generator
  labels:
    name: rc-generator
spec:
  replicas: 1
  selector:
    name: rc-generator
  template:
    metadata:
      labels:
        name: rc-generator
    spec:
      serviceAccount: deployer
      containers:
      - name: master
        image: gordons/rc-generator:v6
        env:
        - name: ROUTER_CERTS_SECRET_NAME
          value: qdrouterd-certs
        - name: ROUTER_CERTS_PATH
          value: /etc/qpid-dispatch/ssl
