---
apiVersion: v1
kind: Template
metadata:
  name: enmasse-secure
objects:
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: queue
    name: secure-queue-inmemory
  objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: queue-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: "${BROKER_IMAGE}"
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: "${COLOCATED_ROUTER_IMAGE}"
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 5671
              name: amqps
              protocol: TCP
            volumeMounts:
            - mountPath: "/etc/qpid-dispatch/ssl"
              name: ssl-certs
              readOnly: true
          volumes:
          - emptyDir: {}
            name: vol-${ADDRESS}
          - name: ssl-certs
            secret:
              secretName: qdrouterd-certs
  parameters:
  - description: The image to use for the broker
    name: BROKER_IMAGE
    value: enmasseproject/artemis:latest
  - description: The image to use for the router
    name: COLOCATED_ROUTER_IMAGE
    value: "${ROUTER_IMAGE}"
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: The address to use for the queue
    name: ADDRESS
    required: true
    value: 2Gi
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: queue
    name: secure-queue-persisted
  objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-${ADDRESS}
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: "${STORAGE_CAPACITY}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: queue-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: "${BROKER_IMAGE}"
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: QUEUE_NAME
              value: "${ADDRESS}"
            image: "${COLOCATED_ROUTER_IMAGE}"
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 5671
              name: amqps
              protocol: TCP
            volumeMounts:
            - mountPath: "/etc/qpid-dispatch/ssl"
              name: ssl-certs
              readOnly: true
          volumes:
          - name: vol-${ADDRESS}
            persistentVolumeClaim:
              claimName: pvc-${ADDRESS}
          - name: ssl-certs
            secret:
              secretName: qdrouterd-certs
  parameters:
  - description: The image to use for the broker
    name: BROKER_IMAGE
    value: enmasseproject/artemis:latest
  - description: The image to use for the router
    name: COLOCATED_ROUTER_IMAGE
    value: "${ROUTER_IMAGE}"
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: The address to use for the queue
    name: ADDRESS
    required: true
    value: 2Gi
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: topic
    name: secure-topic-inmemory
  objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: topic-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${BROKER_IMAGE}"
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${COLOCATED_ROUTER_IMAGE}"
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 5671
              name: amqps
              protocol: TCP
            volumeMounts:
            - mountPath: "/etc/qpid-dispatch/ssl"
              name: ssl-certs
              readOnly: true
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${TOPIC_FORWARDER_IMAGE}"
            name: forwarder
          volumes:
          - emptyDir: {}
            name: vol-${ADDRESS}
          - name: ssl-certs
            secret:
              secretName: qdrouterd-certs
  parameters:
  - description: The image to use for the broker
    name: BROKER_IMAGE
    value: enmasseproject/artemis:latest
  - description: The image to use for the router
    name: COLOCATED_ROUTER_IMAGE
    value: "${ROUTER_IMAGE}"
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: The address to use for the topic
    name: ADDRESS
    required: true
    value: 2Gi
- apiVersion: v1
  kind: Template
  metadata:
    labels:
      addressType: topic
    name: secure-topic-persisted
  objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-${ADDRESS}
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: "${STORAGE_CAPACITY}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: topic-${ADDRESS}
    spec:
      replicas: 1
      selector:
        address: "${ADDRESS}"
        role: broker
      template:
        metadata:
          labels:
            address: "${ADDRESS}"
            capability: router
            role: broker
        spec:
          containers:
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${BROKER_IMAGE}"
            lifecycle:
              preStop:
                exec:
                  command:
                  - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
            name: broker
            ports:
            - containerPort: 5673
              name: amqp
            - containerPort: 61616
              name: core
            volumeMounts:
            - mountPath: "/var/run/artemis"
              name: vol-${ADDRESS}
          - env:
            - name: LINK_CAPACITY
              value: "${ROUTER_LINK_CAPACITY}"
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${COLOCATED_ROUTER_IMAGE}"
            name: router
            ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 5671
              name: amqps
              protocol: TCP
            volumeMounts:
            - mountPath: "/etc/qpid-dispatch/ssl"
              name: ssl-certs
              readOnly: true
          - env:
            - name: TOPIC_NAME
              value: "${ADDRESS}"
            image: "${TOPIC_FORWARDER_IMAGE}"
            name: forwarder
          volumes:
          - name: vol-${ADDRESS}
            persistentVolumeClaim:
              claimName: pvc-${ADDRESS}
          - name: ssl-certs
            secret:
              secretName: qdrouterd-certs
  parameters:
  - description: The image to use for the broker
    name: BROKER_IMAGE
    value: enmasseproject/artemis:latest
  - description: The image to use for the router
    name: COLOCATED_ROUTER_IMAGE
    value: "${ROUTER_IMAGE}"
  - description: The image to use for the topic forwarder
    name: TOPIC_FORWARDER_IMAGE
    value: enmasseproject/topic-forwarder:latest
  - description: The link capacity setting for router
    name: ROUTER_LINK_CAPACITY
    value: '50'
  - description: The address to use for the topic
    name: ADDRESS
    required: true
    value: 2Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: configmap-bridge
    name: configmap-bridge
  spec:
    replicas: 1
    selector:
      name: configmap-bridge
    template:
      metadata:
        labels:
          name: configmap-bridge
      spec:
        containers:
        - image: "${CONFIGMAP_BRIDGE_IMAGE}"
          name: bridge
          ports:
          - containerPort: 5672
            name: amqp
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: ragent
    name: ragent
  spec:
    replicas: 1
    selector:
      name: ragent
    template:
      metadata:
        labels:
          name: ragent
      spec:
        containers:
        - image: "${RAGENT_IMAGE}"
          name: master
          ports:
          - containerPort: 55672
            protocol: TCP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: qdrouterd
    name: qdrouterd
  spec:
    replicas: 1
    selector:
      name: qdrouterd
    template:
      metadata:
        labels:
          capability: router
          name: qdrouterd
      spec:
        containers:
        - env:
          - name: LINK_CAPACITY
            value: "${ROUTER_LINK_CAPACITY}"
          image: "${ROUTER_IMAGE}"
          name: router
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 5671
            name: amqps
            protocol: TCP
          volumeMounts:
          - mountPath: "/etc/qpid-dispatch/ssl"
            name: ssl-certs
            readOnly: true
        volumes:
        - name: ssl-certs
          secret:
            secretName: qdrouterd-certs
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: storage-controller
    name: storage-controller
  spec:
    replicas: 1
    selector:
      name: storage-controller
    template:
      metadata:
        labels:
          name: storage-controller
      spec:
        containers:
        - image: "${STORAGE_CONTROLLER_IMAGE}"
          name: controller
        serviceAccount: deployer
- apiVersion: v1
  kind: Service
  metadata:
    name: messaging
  spec:
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: 5671
    selector:
      capability: router
- apiVersion: v1
  data:
    json: |
      {
          "myqueue": { "store_and_forward":true, "multicast":false, "flavor": "vanilla-queue" },
          "mytopic": { "store_and_forward":true, "multicast":true, "flavor": "vanilla-topic" },
          "anycast": { "store_and_forward":false, "multicast":false },
          "broadcast": { "store_and_forward":false, "multicast":true }
      }
  kind: ConfigMap
  metadata:
    name: maas
- apiVersion: v1
  data:
    json: |
      {
          "vanilla-queue": { "templateName":"queue-inmemory" },
          "vanilla-topic": { "templateName":"topic-inmemory" }
      }
  kind: ConfigMap
  metadata:
    name: flavor
- apiVersion: v1
  kind: Service
  metadata:
    name: ragent
  spec:
    ports:
    - port: 55672
      protocol: TCP
      targetPort: 55672
    selector:
      name: ragent
- apiVersion: v1
  kind: Service
  metadata:
    name: configuration
  spec:
    ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      name: configmap-bridge
parameters:
- description: The image to use for the router
  name: ROUTER_IMAGE
  value: gordons/qdrouterd:latest
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: The image to use for the configmap notification bridge
  name: CONFIGMAP_BRIDGE_IMAGE
  value: enmasseproject/configmap-bridge:latest
- description: The docker image to use for the storage controller
  name: STORAGE_CONTROLLER_IMAGE
  value: enmasseproject/storage-controller:latest
- description: The image to use for the router agent
  name: RAGENT_IMAGE
  value: enmasseproject/ragent:latest
