---
apiVersion: v1
data:
  json: |
    {
        "vanilla-queue": { "templateName":"queue-inmemory" },
     "vanilla-topic": { "templateName":"topic-inmemory" }
    }
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: flavor
